apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deployment-replicas
  labels:
    app: my-k8s-application
    env: prod
    owner: Niyaz
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cia
  template:
    metadata:
      labels:
        app: cia
    spec:
      containers:
        - name: cia-web
          image: niyazbek9393/niyazbek9393:latest3
          ports:
            - containerPort: 80